name: Child Workflow 1

on:
  workflow_call:
    inputs:
      param1:
        type: string
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Print param1
      run: echo " ${{ inputs.param1 }}"
